datasets:
    "textbook":
        scene_path: data/textbook.yaml
        target_path: data/textbook
        target_name_func: "lambda i: f'color_{(int(i)+1):03d}.jpg'"
        # mask_path: masks_undistorted
        # mask_name_func: "lambda i: f'{i}.png'"
prashant-vbb:
    "textbook":
        data_root: /home/prashant/Documents/gitforks/npbg/data
